# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
 workflow_call:
    inputs:
      runner:
        required: true
        type: string
      results-path:
        required: true
        type: string
      results-users:
        required: true
        type: string
          
jobs:            
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
      
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/${{ inputs.results-users }}
      if: (!cancelled())
      with:
        files: ${{ inputs.results-path }}
