name: Build And Test Project

on:
  workflow_call:
    inputs:
      results-path:
        required: true
        type: string
        
    secrets:
      NUGET_KEY:
        required: true   
        
jobs:  
  # === CI and Unit Tests ===
  ci-build-test:   
    name: Deploy to CI
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: (!cancelled())
      with:
        files: ${{ inputs.results-path }}

  # === Deployment to Test ===
  deploy-test:
    name: Deploy to Test
    needs: ci-build-test
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

  # === Deployment to Production ===    
  deploy-prod:
    name: Deploy to Production
    needs: deploy-test
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: PROD 
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0 
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Check release
      id: is_prerelease
      run: |
            if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
              echo "::set-output name=check::true"
            else
              echo "::set-output name=check::false"
            fi
          
    - name: Check for tags using git
      if: steps.is_prerelease.outputs.check == 'true'
      id: check_tags
      run: |
          TAGS=$(git tag --list)
          if [ -z "$TAGS" ]; then
            echo "::set-output name=has_tags::false"
          else
            echo "::set-output name=has_tags::true"
          fi   
          
    - name: Find latest tag
      if: steps.check_tags.outputs.has_tags == 'true'
      id: find_latest_tag
      uses: oprypin/find-latest-tag@v1
      with:
          repository: ${{ github.repository }}
          releases-only: false
          prefix: "v"
          
    - name: Get latest tag
      if: steps.is_prerelease.outputs.check == 'true'
      id: latest_tag
      run: |
          if [[ "${{ steps.check_tags.outputs.has_tags }}" == "true" ]]; then
              echo "latest_tag=${{ steps.find_latest_tag.outputs.tag }}" >> $GITHUB_OUTPUT
            else
              echo "latest_tag=v0.0.0" >> $GITHUB_OUTPUT
            fi
      
    - name: Check tag pre release
      id: check_tag_pre_release
      if: contains(steps.latest_tag.outputs.latest_tag, 'build')
      run: echo "check=true" >> $GITHUB_OUTPUT
        
    - name: Calculate new version
      if: steps.is_prerelease.outputs.check == 'true'
      id: calculate_new_version
      run: |
            LAST_TAG=${{ steps.latest_tag.outputs.latest_tag }}
            VERSION_CORE=$(echo $LAST_TAG | sed 's/^v//')

            if [[ "${{ steps.check_tag_pre_release.outputs.check }}" == "true" ]]; then
              NEW_VERSION_CORE=$(echo $VERSION_CORE | awk -F'.' -v OFS='.' '{$NF = $NF + 1;}1')
              echo "new_version=$NEW_VERSION_CORE" >> $GITHUB_OUTPUT
            else
              echo "new_version=$VERSION_CORE-build.1" >> $GITHUB_OUTPUT
            fi

    - name: Get tag
      if: steps.is_prerelease.outputs.check == 'false'
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        strip_v: false
        
    - name: Calculate new version
      id: new_version
      run: |
            if [[ "${{ steps.is_prerelease.outputs.check }}" == "false" ]]; then
              echo "new_version=${{ steps.tag.outputs.tag }}" >> $GITHUB_OUTPUT
            else
              echo "new_version=${{ steps.calculate_new_version.outputs.new_version }}" >> $GITHUB_OUTPUT
            fi
            
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ steps.new_version.outputs.new_version  }}"
        release_name: "Pre-Release v${{ steps.new_version.outputs.new_version }}"
        draft: false
        prerelease: ${{ steps.is_prerelease.outputs.check }}
          
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack NuGet package
      run: dotnet pack --configuration Release --no-build --output nupkgs/ /p:Version=${{ steps.new_version.outputs.new_version }}
    - name: Publish NuGet package
      run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.NUGET_KEY  }} --source https://api.nuget.org/v3/index.json
