name: Build And Test Project

on:
  workflow_dispatch:
    inputs:
      project-path:
        type: string
        default: "--no-build --verbosity normal"
      results-path:
        required: true
        type: string
          
jobs:  
  build-and-test-project:
    strategy:
      matrix:
        project-path: ${{ fromJSON(github.event.inputs.project-path) }}
        
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      #run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
      run: dotnet test ${{ matrix.project-path }} --logger "trx;LogFileName=test-results.trx"
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      if: (!cancelled())
      with:
        files: ${{ inputs.results-path }}
