name: Deploy

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
        
      environment:
        required: true
        type: string

    secrets:
      SERVER_HOST:
        required: true

      SERVER_USER:
        required: true

      SERVER_SSH_KEY:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Resolve deployment path2
        run: |
         echo "App: ${{ inputs.app-name }}"
         echo "Environment: ${{ inputs.environment }}"
          
      - name: Resolve deployment path
        id: deployment-path
        shell: pwsh
        run: |
          $basePath = "C:\inetpub\wwwroot"
          $appName = "${{ inputs.app-name }}"
          $environment = "${{ inputs.environment }}"

          $paths = @{
            ci   = "$basePath\$appName-ci"
            test = "$basePath\$appName-test"
            prob = "$basePath\$appName-prob"
          }

          $path = $paths[$environment]

          if (-not $path) {
            throw "Invalid environment: $environment"
          }

          "path=$path" >> $env:GITHUB_OUTPUT

      - name: Deploy application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd "${{ steps.deployment-path.outputs.path }}"
            git pull origin main
            powershell -ExecutionPolicy Bypass -File deploy.ps1
