name: Run Tests

on:
  workflow_call:
    inputs:
      results-path:
        required: true
        type: string
jobs:
  run-tests:
    runs-on: ubuntu-latest # GitHub-hosted runners provide a Docker environment by default

    steps:
      - uses: actions/checkout@v4 # Checkout your repository code
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Specify your .NET version
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run Tests
        run: dotnet test ./src/Beep.Database.Mapper.Tests.Integration/Beep.Database.Mapper.Tests.Integration.csproj --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: ${{ inputs.results-path }}
