name: Get tag

on:
  workflow_call:
    inputs:
      environment_name:
            description: 'Name of the environment to deploy to'
            required: true
            type: string
            
    outputs:
      new_version:
        value: ${{ jobs.get-tag.outputs.new_version }}                              
jobs:  
  get-tag:
    name: Get tag
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    outputs:
      new_version: ${{ steps.calculate_new_version.outputs.new_version }}
      
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
       with:
            fetch-depth: 0 
          
     - name: Setup .NET
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: 8.0.x

     - name: Check for tags using git
       id: check_tags
       run: |
          TAGS=$(git tag --list)
          if [ -z "$TAGS" ]; then
            echo "::set-output name=has_tags::false"
          else
            echo "::set-output name=has_tags::true"
          fi   
          
     - name: Find latest tag
       if: steps.check_tags.outputs.has_tags == 'true'
       id: find_latest_tag
       uses: oprypin/find-latest-tag@v1
       with:
          repository: ${{ github.repository }}
          releases-only: false
          prefix: "v"
          
     - name: Get latest tag
       id: latest_tag
       run: |
          if [[ "${{ steps.check_tags.outputs.has_tags }}" == "true" ]]; then
              echo "latest_tag=${{ steps.find_latest_tag.outputs.tag }}" >> $GITHUB_OUTPUT
            else
              echo "latest_tag=v0.0.0" >> $GITHUB_OUTPUT
            fi
      
     - name: Check tag pre release
       id: check_tag_pre_release
       if: contains(steps.latest_tag.outputs.latest_tag, 'build')
       run: echo "check=true" >> $GITHUB_OUTPUT
        
     - name: Calculate new version name
       id: calculate_new_version
       run: |
            LAST_TAG=${{ steps.latest_tag.outputs.latest_tag }}
            VERSION_CORE=$(echo $LAST_TAG | sed 's/^v//')

            if [[ "${{ steps.check_tag_pre_release.outputs.check }}" == "true" ]]; then
              NEW_VERSION_CORE=$(echo $VERSION_CORE | awk -F'.' -v OFS='.' '{$NF = $NF + 1;}1')
              echo "new_version=$NEW_VERSION_CORE" >> $GITHUB_OUTPUT
            else
              echo "new_version=$VERSION_CORE-build.1" >> $GITHUB_OUTPUT
            fi

     - name: Create Pre-Release
       uses: actions/create-release@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         tag_name: "v${{ steps.calculate_new_version.outputs.new_version  }}"
         release_name: "Pre-Release v${{ steps.calculate_new_version.outputs.new_version }}"
         draft: false
         prerelease: true
