name: Get tag

on:
  workflow_call:            
    outputs:
      new_version:
        value: ${{ jobs.get-tag.outputs.new_version }}                              
jobs:  
  get-tag:
    name: Get tag
    runs-on: ubuntu-latest
    environment: DEV
    outputs:
      new_version: ${{ steps.get-tag.outputs.new_version }}
      
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
       with:
            fetch-depth: 0 
          
     - name: Setup .NET
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: 8.0.x

     - name: Get tag
       if: startsWith(github.ref, 'refs/tags/v')
       id: tag-release
       run: |
          TAG_REF="${{ github.ref }}"
          VERSION=$(echo "$TAG_REF" | sed -E 's/^refs\/tags\/v?([0-9.]*).*$/\1/')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        
     - name: Check for tags using git
       if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
       id: check_tags
       run: |
          TAGS=$(git tag --list)
          if [ -z "$TAGS" ]; then
            echo "::set-output name=has_tags::false"
          else
            echo "::set-output name=has_tags::true"
          fi   
          
     - name: Find latest tag
       if: steps.check_tags.outputs.has_tags == 'true'
       id: find_latest_tag
       uses: oprypin/find-latest-tag@v1
       with:
          repository: ${{ github.repository }}
          releases-only: false
          prefix: "v"
          
     - name: Get latest tag
       if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
       id: latest_tag
       run: |
          if [[ "${{ steps.check_tags.outputs.has_tags }}" == "true" ]]; then
              echo "latest_tag=${{ steps.find_latest_tag.outputs.tag }}" >> $GITHUB_OUTPUT
            else
              echo "latest_tag=v0.0.0" >> $GITHUB_OUTPUT
            fi
      
     - name: Check tag pre release
       id: check_tag_pre_release
       if: contains(steps.latest_tag.outputs.latest_tag, 'build')
       run: echo "check=true" >> $GITHUB_OUTPUT
        
     - name: Calculate new version
       if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
       id: tag-pre-release
       run: |
            LAST_TAG=${{ steps.latest_tag.outputs.latest_tag }}
            VERSION_CORE=$(echo $LAST_TAG | sed 's/^v//')

            if [[ "${{ steps.check_tag_pre_release.outputs.check }}" == "true" ]]; then
              NEW_VERSION_CORE=$(echo $VERSION_CORE | awk -F'.' -v OFS='.' '{$NF = $NF + 1;}1')
              echo "new_version=$NEW_VERSION_CORE" >> $GITHUB_OUTPUT
            else
              echo "new_version=$VERSION_CORE-build.1" >> $GITHUB_OUTPUT
            fi
            
     - name: Get latest tag
       id: get-tag
       run: |
         if [[ "${{ steps.tag-release.outputs.version }}" == "" ]]; then
              echo "new_version=${{ steps.tag-pre-release.outputs.new_version }}" >> $GITHUB_OUTPUT
            else
              echo "new_version=${{ steps.tag-release.outputs.version }}" >> $GITHUB_OUTPUT
          fi
          
     - name: Get latest tag a
       run: echo ${{ steps.get-tag.outputs.new_version }}
