name: Publish Pre Release

on:
  workflow_call:
    inputs:
      new_version:
        required: true
        type: string
      solution-path:
        required: false
        type: string
        default: ''
        
    secrets:
      NUGET_KEY:
        required: true
jobs:
  build:
    name: Publish NuGet Package
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0 
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Calculate new tag name
      id: calculate_new_tag
      run: |             
              NEW_VERSION_CORE= ${{ inputs.new_version  }}
              NEW_TAG="v$NEW_VERSION_CORE"
              echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
           
    - name: Create Pre-Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.calculate_new_tag.outputs.new_tag  }}
        release_name: Pre-Release ${{ steps.calculate_new_tag.outputs.new_tag }}
        draft: false
        prerelease: true
          
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack NuGet package
      run: dotnet pack ${{ inputs.solution-path }} --configuration Release --no-build --output nupkgs/ /p:Version=${{ inputs.new_versionn }}
    - name: Publish NuGet package
      run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.NUGET_KEY  }} --source https://api.nuget.org/v3/index.json
            
