name: Publish NuGet Package

on:
  workflow_call:
    secrets:
      NUGET_KEY:
        required: true
jobs:
  build:
    name: Publish NuGet Package
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        strip_v: true
              
    - name: Pack NuGet package
      run: dotnet pack --configuration Release --no-build --output nupkgs/ /p:Version=${{ steps.tag.outputs.tag }}
    - name: Publish NuGet package
      run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
